version: "3.8"
services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: restaurant-management
    ports:
      - "27017:27017"
  
  app:
    image: restaurant-management-server:latest
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "9000:9000"
    environment:
      - PORT=9000
      - MONGODB_URL=mongodb://mongo:27017/restaurant-management
      - SECRET_KEY=s3cr3t
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:9000/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3

  mongo-express:
    image: mongo-express:1.0
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    ports:
      - "8081:8081"
    depends_on:
      - mongo

volumes:
  mongo-data: